apiVersion: v1
kind: Secret
metadata:
  name: ostoy-secret
  namespace: ostoy
type: Opaque
data:
  secret.txt: >-
    VVNFUk5BTUU9bXlfdXNlcgpQQVNTV09SRD1AT3RCbCVYQXAhIzYzMlk1RndDQE1UUWsKU01UUD1sb2NhbGhvc3QKU01UUF9QT1JUPTI1
