apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ostoy-pvc
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G
